# Generated by Django 4.2.30 on 2026-06-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_finalize_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='rammodule',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Изображение'),
        ),
    ]
