# Generated by Django 4.2.30 on 2026-06-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rammodule_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rammodule',
            name='memory_type',
            field=models.CharField(blank=True, choices=[('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=10, verbose_name='Тип памяти'),
        ),
    ]
