# Generated by Django 4.2.30 on 2026-06-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_rammodule_memory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rammodule',
            name='ecc',
            field=models.BooleanField(default=False, verbose_name='ECC'),
        ),
        migrations.AddField(
            model_name='rammodule',
            name='form_factor',
            field=models.CharField(blank=True, choices=[('DIMM', 'DIMM'), ('SO-DIMM', 'SO-DIMM'), ('Mini-DIMM', 'Mini-DIMM')], max_length=10, verbose_name='Форм-фактор'),
        ),
        migrations.AddField(
            model_name='rammodule',
            name='has_expo',
            field=models.BooleanField(default=False, verbose_name='AMD EXPO'),
        ),
        migrations.AddField(
            model_name='rammodule',
            name='modules_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во модулей'),
        ),
        migrations.AddField(
            model_name='rammodule',
            name='rank',
            field=models.CharField(blank=True, choices=[('1R', 'Одноранговая'), ('2R', 'Двухранговая')], max_length=2, verbose_name='Ранговость'),
        ),
        migrations.AddField(
            model_name='rammodule',
            name='timing_cl',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='CAS-латентность'),
        ),
        migrations.AddField(
            model_name='rammodule',
            name='timings',
            field=models.CharField(blank=True, max_length=30, verbose_name='Тайминги'),
        ),
        migrations.AddField(
            model_name='rammodule',
            name='voltage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Напряжение, В'),
        ),
        migrations.AddField(
            model_name='rammodule',
            name='xmp_version',
            field=models.CharField(blank=True, max_length=10, verbose_name='Профиль XMP'),
        ),
    ]
